/*
* generated by Xtext
*/
package org.inria.wordpress.wdpdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WdpDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.inria.wordpress.wdpdsl.ui.internal.WdpDslActivator.getInstance().getInjector("org.inria.wordpress.wdpdsl.WdpDsl");
	}
	
}
