/*
* generated by Xtext
*/
package org.inria.wordpress.wdpdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WdpDslStandaloneSetup extends WdpDslStandaloneSetupGenerated{

	public static void doSetup() {
		new WdpDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

