<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extendedcontentfwk" nsURI="http://inria/atlanmod/extendedcontentfwk"
    nsPrefix="extendedcontentfwk">
  <eClassifiers xsi:type="ecore:EClass" name="TranslatedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation_EN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedLogicalApplicationComponent"
      eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//LogicalApplicationComponent #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedDataEntity" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//DataEntity #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedInformationSystemService" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//InformationSystemService #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedPhysicalApplicationComponent"
      eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//PhysicalApplicationComponent #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedFunction" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//Function #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedProduct" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//Product #//TranslatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isBasedOn" upperBound="-1"
        eType="#//ExtendedPhysicalApplicationComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedBusinessService" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//BusinessService #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedRole" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//Role #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedProcess" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//Process #//TranslatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isDocumentedBy" eType="#//Document"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedActor" eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//Actor #//TranslatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//TranslatedElement http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lien_FR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lien_EN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedPhysicalTechnologyComponent"
      eSuperTypes="http://www.obeonetwork.org/dsl/togaf/contentfwk/9.0.0#//PhysicalTechnologyComponent #//TranslatedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
