/*
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.inria.wordpress.wdpdsl.ui.internal.WdpDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WdpDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WdpDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WdpDslActivator.getInstance().getInjector(WdpDslActivator.ORG_INRIA_WORDPRESS_WDPDSL_WDPDSL);
	}
	
}
