<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wdpDsl" nsURI="http://www.inria.org/wordpress/wdpdsl/WdpDsl"
    nsPrefix="wdpDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Website">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adminUser" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posts" upperBound="-1"
        eType="#//Post" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearance" eType="#//Appearance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaLibrary" upperBound="-1"
        eType="#//Media" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalities" upperBound="-1"
        eType="#//Functionality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" eType="#//Settings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deletion" eType="#//Deletion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deletion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postsByTitle" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pagesByTitle" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usersByLogin" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediasByTitle" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionalitiesByName"
        unique="false" upperBound="-1" eType="#//functionalities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="themesByName" unique="false"
        upperBound="-1" eType="#//themes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoriesByName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagsByName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="menusByName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commentsByPostDateAuthor"
        upperBound="-1" eType="#//PostDateAuthor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostDateAuthor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentAuthorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userRole" eType="#//role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webSite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biography" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostPage_Impl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//pageStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuredImage" eType="#//Image"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonAttributes" eType="#//PostPage_Impl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Post" eSuperTypes="#//PostPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" unique="false"
        upperBound="-1" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//postFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//PostPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationDateGMT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Appearance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
        eType="#//Widget" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearanceMenus" upperBound="-1"
        eType="#//Menu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearanceHeader" eType="#//Header"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theme" upperBound="-1"
        eType="#//Theme" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Theme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="themeType" eType="#//themes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPlugin" eType="#//Plugin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functionality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionalityType" eType="#//functionalities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="socialNetworks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPlugin" eType="#//Plugin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commentPostPage" eType="#//PostPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Url">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetFeed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingItemContent"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingItemAuthor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingItemDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//Url" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//Url" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//Url" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uploadedTo" eType="#//PostPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//Url" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//Url" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uploadImage" eType="#//Url"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingHeaderText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Taxonomy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slug" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Taxonomy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//Taxonomy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Settings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" eType="#//GeneralSettings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writing" eType="#//WritingSettings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reading" eType="#//ReadingSettings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discussion" eType="#//DiscussionSettings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="media" eType="#//MediaSettings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permalinks" eType="#//PermalinksSettings"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="postFormat">
    <eLiterals name="standard" literal="standard"/>
    <eLiterals name="aside" value="1" literal="aside"/>
    <eLiterals name="audio" value="2" literal="audio"/>
    <eLiterals name="chat" value="3" literal="chat"/>
    <eLiterals name="gallery" value="4" literal="gallery"/>
    <eLiterals name="image" value="5" literal="image"/>
    <eLiterals name="link" value="6" literal="link"/>
    <eLiterals name="quote" value="7" literal="quote"/>
    <eLiterals name="status" value="8" literal="status"/>
    <eLiterals name="video" value="9" literal="video"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="websiteTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="websiteTagline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="websiteAdress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adminMail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefaultRole" eType="#//role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeZone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gsDateFormat" eType="#//dateformat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gsTimeFormat" eType="#//timeFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekStartsOn" eType="#//weeks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wordPressAdress" eType="#//Url"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WritingSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mailServer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loginName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPostCategory" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMailCategory" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConvertingEmoticons"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCorrectingInvalidXHTML"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadingSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNumberPostsForBlogPages"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberRecentItemForFeeds"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticFrontPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticPostPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingLastPostInFront"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIndexed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingFullTextForFeed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscussionSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberArticleDaysForAutoCloseComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nestedCommentsLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberCommentsPerPageForBreakedComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLinksInCommentForModeration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moderatedWords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forbiddenWords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAvatarRating" eType="#//avatarRating"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefaultAvatar" eType="#//defaultAvatar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNotifyingLinkedBlogs"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAllowingLinkNotificationsFromBlogs"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAllowingPublicComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAskingNameAndMailCommentAuthor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAllowingAnonymousComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBreakingCommentsIntoPages"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isdisplayingLastPageForBreakedComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingOlderCommentForEachPage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMailingAdminForEachComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHeldingCommentForModeration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAskingAdminApprovement"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAskingPreviousAdminApprovement"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingAvatar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCroppingThumbnailToExactDims"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrganizeUploadsIntoFolders"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PermalinksSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permaUrlForm" eType="#//urlForm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlCategoryBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlTagBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//widgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetArchives" upperBound="-1"
        eType="#//Archive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendars" upperBound="-1"
        eType="#//Calendar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//WidgetCategorie" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customMenus" upperBound="-1"
        eType="#//WidgetMenu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metas" upperBound="-1"
        eType="#//Meta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//WidgetPage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recentComments" upperBound="-1"
        eType="#//WidgetComment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recentPosts" upperBound="-1"
        eType="#//WidgetPost" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feeds" upperBound="-1"
        eType="#//WidgetFeed" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="searchs" upperBound="-1"
        eType="#//Search" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tagClouds" upperBound="-1"
        eType="#//TagCloud" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="texts" upperBound="-1"
        eType="#//Text" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="menuName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" unique="false" upperBound="-1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" unique="false"
        upperBound="-1" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentMenuSetting" eType="#//CurrentMenuSetting"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingAsDropDown"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingPostsCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calendar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetCategorie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDisplayedPosts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingSubCat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDropDownList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetMenu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedMenu" eType="#//Menu"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetPagesSorter" eType="#//pagesSorter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idPageExcluded" eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetComment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDisplayedComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetPost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDisplayedPosts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingPostDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Search">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagCloud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxonomy" eType="#//taxonomyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutoParagraphs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CurrentMenuSetting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAddingNewTopLevelPages"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigationMenuLocated"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="avatarRating">
    <eLiterals name="G" literal="G"/>
    <eLiterals name="PG" value="1" literal="PG"/>
    <eLiterals name="R" value="2" literal="R"/>
    <eLiterals name="X" value="3" literal="X"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="dateformat">
    <eLiterals name="jnY" literal="j/n/Y"/>
    <eLiterals name="FjY" value="1" literal="F j, Y"/>
    <eLiterals name="Ynj" value="2" literal="Y/n/j"/>
    <eLiterals name="njY" value="3" literal="n/j/Y"/>
    <eLiterals name="custom" value="4" literal="custom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="defaultAvatar">
    <eLiterals name="mysteryMan" literal="mystery"/>
    <eLiterals name="blank" value="1" literal="blank"/>
    <eLiterals name="GravatarLogo" value="2" literal="gravatar_default"/>
    <eLiterals name="identicon" value="3" literal="identicon"/>
    <eLiterals name="wavatar" value="4" literal="wavatar"/>
    <eLiterals name="monsterId" value="5" literal="monsterid"/>
    <eLiterals name="retro" value="6" literal="retro"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="functionalities">
    <eLiterals name="eCommerce" literal="eCommerce"/>
    <eLiterals name="forms" value="1" literal="forms"/>
    <eLiterals name="hamSpam" value="2" literal="hamSpam"/>
    <eLiterals name="indexing" value="3" literal="indexing"/>
    <eLiterals name="multiLanguage" value="4" literal="multiLanguage"/>
    <eLiterals name="pictures" value="5" literal="pictures"/>
    <eLiterals name="SEO" value="6" literal="seo"/>
    <eLiterals name="socialNetwork" value="7" literal="socialNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="themes">
    <eLiterals name="responsive" literal="responsive"/>
    <eLiterals name="SEO" value="1" literal="seo"/>
    <eLiterals name="headerParallaxEffect" value="2" literal="headerParallaxEffect"/>
    <eLiterals name="business" value="3" literal="business"/>
    <eLiterals name="magazine" value="4" literal="magazine"/>
    <eLiterals name="galleries" value="5" literal="galleries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="pagesSorter">
    <eLiterals name="pageTitle" literal="page_title"/>
    <eLiterals name="pageOrder" value="1" literal="menu_order"/>
    <eLiterals name="pageId" value="2" literal="page_id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="pageStatus">
    <eLiterals name="published" literal="publish"/>
    <eLiterals name="pendingreview" value="1" literal="pending"/>
    <eLiterals name="draft" value="2" literal="draft"/>
    <eLiterals name="autoDraft" value="3" literal="auto-draft"/>
    <eLiterals name="trash" value="4" literal="trash"/>
    <eLiterals name="private" value="5" literal="private"/>
    <eLiterals name="new" value="6" literal="new"/>
    <eLiterals name="inherit" value="7" literal="inherit"/>
    <eLiterals name="future" value="8" literal="future"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="role">
    <eLiterals name="author" literal="author"/>
    <eLiterals name="administrator" value="1" literal="administrator"/>
    <eLiterals name="suscriber" value="2" literal="subscriber"/>
    <eLiterals name="editor" value="3" literal="editor"/>
    <eLiterals name="contributor" value="4" literal="contributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="timeFormat">
    <eLiterals name="g_i_aLower" literal="g:i a"/>
    <eLiterals name="g_i_AUpper" value="1" literal="g:i A"/>
    <eLiterals name="Gg" value="2" literal="G:g"/>
    <eLiterals name="custom" value="3" literal="custom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="taxonomyType">
    <eLiterals name="categories" literal="category"/>
    <eLiterals name="tags" value="1" literal="post_tag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="urlForm">
    <eLiterals name="default" literal="defaultForm"/>
    <eLiterals name="dayAndName" value="1" literal="dayAndName"/>
    <eLiterals name="monthAndName" value="2" literal="monthAndName"/>
    <eLiterals name="numeric" value="3" literal="numeric"/>
    <eLiterals name="postName" value="4" literal="postName"/>
    <eLiterals name="customStructure" value="5" literal="customStructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="weeks">
    <eLiterals name="monday" literal="Monday"/>
    <eLiterals name="tuesday" value="1" literal="Tuesday"/>
    <eLiterals name="wednesday" value="2" literal="Wednesday"/>
    <eLiterals name="thirsday" value="3" literal="Thursday"/>
    <eLiterals name="friday" value="4" literal="Friday"/>
    <eLiterals name="saturday" value="5" literal="Saturday"/>
    <eLiterals name="sunday" value="6" literal="Sunday"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="widgetType">
    <eLiterals name="mainArea" literal="mainArea"/>
    <eLiterals name="secondaryArea" value="1" literal="secondaryArea"/>
  </eClassifiers>
</ecore:EPackage>
