/*
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.inria.wordpress.wdpdsl.wdpDsl.User;
import org.inria.wordpress.wdpdsl.wdpDsl.Website;
import org.inria.wordpress.wdpdsl.wdpDsl.impl.UserImpl;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class WdpDslScopeProvider extends org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider {

//	public IScope getScope(EObject context, EReference reference) {
//		
//		if (reference instanceof UserImpl) {
//			Website ws = (Website)context;
//			System.out.println(reference.getName());
//		}
//		
//		
//		return super.getScope(context, reference);		
//	}
	
//	IScope scope_Website_adminUser(Website website, EReference ref) {
//		System.out.println(ref);
//        return Scopes.scopeFor(website.getUsers());
//    }
	
}
