/**
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.validation;

import org.inria.wordpress.wdpdsl.validation.AbstractWdpDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class WdpDslValidator extends AbstractWdpDslValidator {
}
