<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="WordPressConfiguration" nsURI="http://www.inria.fr/modeling/cms/WordPressConfiguration"
    nsPrefix="WordPressConfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="Website">
    <eStructuralFeatures xsi:type="ecore:EReference" name="posts" upperBound="-1"
        eType="#//Post"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" eType="#//Settings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearance" eType="#//Apperance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaLibrary" upperBound="-1"
        eType="#//Media"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalities" upperBound="-1"
        eType="#//Functionality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" upperBound="-1" eType="#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adminUser" eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Apperance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
        eType="#//Widget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearanceMenus" upperBound="-1"
        eType="#//Menu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearanceHeader" eType="#//Header"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theme" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Avatar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentPicture" eType="#//Url"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Taxonomy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commentPostPage" eType="#//PostPage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CurrentMenuSetting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAddingNewTopLevelPages"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigationMenuLocated"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deletion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pagesByTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usersByLogin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediasByTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionnalitiesByName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginsByfileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoriesByName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TagsByName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MenusByName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CommentsByPostDateAuthor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feed" eSuperTypes="#//Url">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functionality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionalityType" eType="#//functionalities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPlugin" eType="#//Plugin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idFunctionality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="socialNetworks" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultImage" eType="#//defaultImageHeader"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingHeaderText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uploadImage" eType="#//Url"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Url">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idLink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media" eSuperTypes="#//Url">
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uploadedTo" eType="#//PostPage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idMedia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentMenuSetting" eType="#//CurrentMenuSetting"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//pageStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuredImage" eType="#//Image"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedMedia" eType="#//Media"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//PostPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOfPublication" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Post" eSuperTypes="#//PostPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCategory" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" eType="#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//postFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idPost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" eSuperTypes="#//Url">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Search">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idSearch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Settings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" eType="#//GeneralSettings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writing" eType="#//WritingSettings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reading" eType="#//ReadingSettings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discussion" eType="#//DiscussionSettings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="media" eType="#//MediaSettings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permalinks" eType="#//PermalinksSettings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralSettings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wordPressAdress" eType="#//Url"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adminMail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefaultRole" eType="#//role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeZone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" eType="#//dateFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeFormat" eType="#//timeFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekStartsOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customDateFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostDateAuthor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadingSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingLastPostInFront"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticFrontPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticPostPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNumberPostsForBlogPages"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberRecentItemForFeeds"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIndexed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingFullTextForFeed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscussionSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNotifyingLinkedBlogs"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAllowingLinkNotificationsFromBlogs"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAllowingPublicComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAskingNameAndMailCommentAuthor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAllowingAnonymousComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberArticleDaysForAutoCloseComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nestedCommentsLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBreakingCommentsIntoPages"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberCommentsPerPageForBreakedComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isdisplayingLastPageForBreakedComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingOlderCommentForEachPage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMailingAdminForEachComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHeldingCommentForModeration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAskingAdminApprovement"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAskingPreviousAdminApprovement"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLinksInCommentForModeration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moderatedWords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forbiddenWords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingAvatar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAvatarRating" eType="#//avatarRating"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefaultAvatar" eType="#//defaultAvatar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCroppingThumbnailToExactDims"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrganizeUploadsIntoFolders"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PermalinksSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlForm" eType="#//urlForm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlCategoryBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlTagBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//Url">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//Taxonomy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Taxonomy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slug" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posts" upperBound="-1"
        eType="#//Post"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutoParagraphs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userRole" eType="#//role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userAvatar" eType="#//Avatar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webSite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biography" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idUser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetArchives" upperBound="-1"
        eType="#//Archives"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendars" upperBound="-1"
        eType="#//Calendars"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//WidgetCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customMenus" upperBound="-1"
        eType="#//WidgetMenu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metas" upperBound="-1"
        eType="#//Meta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//WidgetPage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recentComments" upperBound="-1"
        eType="#//WidgetComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recentPosts" upperBound="-1"
        eType="#//WidgetPost"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feeds" upperBound="-1"
        eType="#//WidgetFeed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="searchs" upperBound="-1"
        eType="#//Search"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tagClouds" upperBound="-1"
        eType="#//TagCloud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="texts" upperBound="-1"
        eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//widgetType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calendars">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idCalendar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archives">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingAsDropDown"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShowingPostsCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idArchives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idWidgetCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetMenu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedMenu" eType="#//Menu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idWidgetMenu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetPagesSorter" eType="#//pagesSorter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idPageExcluded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idWidgetPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetComment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDisplayedComments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idWidgetComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetPost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDisplayedPosts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingPostDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idWidgetPost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetFeed" eSuperTypes="#//Feed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingItemContent"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingItemAuthor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayingItemDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idWidgetFeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagCloud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idTagCloud" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxonomy" eType="#//taxonomyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Url">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WritingSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConvertingEmoticons"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCorrectingInvalidXHTML"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPostCategory" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mailServer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loginName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMailCategory" eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="defaultImageHeader">
    <eLiterals name="firstImageHeader"/>
    <eLiterals name="secondImageHeader" value="1"/>
    <eLiterals name="thirdImageHeader" value="2"/>
    <eLiterals name="randomImageHeader" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="functionalities">
    <eLiterals name="eBuisiness"/>
    <eLiterals name="forms" value="1"/>
    <eLiterals name="hamSpam" value="2"/>
    <eLiterals name="indexing" value="3"/>
    <eLiterals name="multiLanguage" value="4"/>
    <eLiterals name="pictures" value="5"/>
    <eLiterals name="SEO" value="6"/>
    <eLiterals name="socialNetwork" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="role">
    <eLiterals name="Subscriber"/>
    <eLiterals name="Administrator" value="1" literal="Administrator"/>
    <eLiterals name="Editor" value="2"/>
    <eLiterals name="Author" value="3"/>
    <eLiterals name="Contributor" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="widgetType">
    <eLiterals name="mainArea"/>
    <eLiterals name="secondaryArea" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="pagesSorter">
    <eLiterals name="page_title"/>
    <eLiterals name="page_order" value="1"/>
    <eLiterals name="page_id" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="postFormat">
    <eLiterals name="standard"/>
    <eLiterals name="aside" value="1"/>
    <eLiterals name="audio" value="2"/>
    <eLiterals name="chat" value="3"/>
    <eLiterals name="gallery" value="4"/>
    <eLiterals name="image" value="5"/>
    <eLiterals name="link" value="6"/>
    <eLiterals name="quote" value="7"/>
    <eLiterals name="status" value="8"/>
    <eLiterals name="video" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="pageStatus">
    <eLiterals name="publish"/>
    <eLiterals name="pending" value="1"/>
    <eLiterals name="draft" value="2"/>
    <eLiterals name="public" value="3"/>
    <eLiterals name="private" value="4"/>
    <eLiterals name="new" value="5"/>
    <eLiterals name="inherit" value="6"/>
    <eLiterals name="trash" value="7"/>
    <eLiterals name="future" value="8"/>
    <eLiterals name="auto-draft" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="pageVisibility">
    <eLiterals name="public"/>
    <eLiterals name="passwordProtected" value="1"/>
    <eLiterals name="private" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="avatarRating">
    <eLiterals name="G"/>
    <eLiterals name="PG" value="1"/>
    <eLiterals name="R" value="2"/>
    <eLiterals name="X" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="defaultAvatar">
    <eLiterals name="mysteryMan"/>
    <eLiterals name="Blank" value="1"/>
    <eLiterals name="GravatarLogo" value="2"/>
    <eLiterals name="identicon" value="3"/>
    <eLiterals name="wavatar" value="4"/>
    <eLiterals name="monsterId" value="5"/>
    <eLiterals name="retro" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="urlForm">
    <eLiterals name="default"/>
    <eLiterals name="dayAndName" value="1"/>
    <eLiterals name="monthAndName" value="2"/>
    <eLiterals name="numeric" value="3"/>
    <eLiterals name="postName" value="4"/>
    <eLiterals name="customStructure" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="dateFormat">
    <eLiterals name="F j, Y" literal="F j, Y"/>
    <eLiterals name="Y/n/j" value="1"/>
    <eLiterals name="n/j/Y" value="2"/>
    <eLiterals name="j/n/Y" value="3"/>
    <eLiterals name="custom" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="timeFormat">
    <eLiterals name="g:i a" literal="g:i a"/>
    <eLiterals name="g:i A" value="1"/>
    <eLiterals name="G:g" value="2"/>
    <eLiterals name="custom" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="taxonomyType">
    <eLiterals name="category"/>
    <eLiterals name="post_tag" value="1"/>
  </eClassifiers>
</ecore:EPackage>
