/*
* generated by Xtext
*/
package org.inria.wordpress.wdpdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.inria.wordpress.wdpdsl.services.WdpDslGrammarAccess;

public class WdpDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private WdpDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.inria.wordpress.wdpdsl.parser.antlr.internal.InternalWdpDslParser createParser(XtextTokenStream stream) {
		return new org.inria.wordpress.wdpdsl.parser.antlr.internal.InternalWdpDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Website";
	}
	
	public WdpDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WdpDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
