/*
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.ui.contentassist

import org.inria.wordpress.wdpdsl.ui.contentassist.AbstractWdpDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class WdpDslProposalProvider extends AbstractWdpDslProposalProvider {
}
