/*
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WdpDslUiModule extends org.inria.wordpress.wdpdsl.ui.AbstractWdpDslUiModule {
	public WdpDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
