/**
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class WdpDslFormatter extends AbstractDeclarativeFormatter {
  protected void configureFormatting(final FormattingConfig c) {
  }
}
