/*
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WdpDslRuntimeModule extends org.inria.wordpress.wdpdsl.AbstractWdpDslRuntimeModule {

}
