/*
 * generated by Xtext
 */
package org.inria.wordpress.wdpdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractWdpDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.inria.wordpress.wdpdsl.wdpDsl.WdpDslPackage.eINSTANCE);
		return result;
	}
}
